USE Traces

DROP TABLE IF EXISTS TESTE_SLEEPING

CREATE TABLE TESTE_SLEEPING (
	Id INT IDENTITY(1,1) NOT NULL,
	Ds_Descricao VARCHAR(13) NOT NULL
)

--	INSERE UM REGISTRO NA TABELA (COMENTAR SOBRE O IDENTITY)
INSERT INTO TESTE_SLEEPING (Ds_Descricao)
VALUES ('Dirceu gordãoooo')

INSERT INTO TESTE_SLEEPING (Ds_Descricao)
VALUES ('Dirceu gordão')

SELECT * FROM TESTE_SLEEPING
GO

--	1) EXECUTAR O CODIGO ABAIXO EM OUTRA QUERY (QUERY 1)
USE Traces

BEGIN TRAN
	UPDATE TESTE_SLEEPING
	SET Ds_Descricao = 'Dirceu gordo'
	WHERE Id = 2

	--	SELECT 2

	--	SELECT 3

	UPDATE TESTE_SLEEPING
	SET Ds_Descricao = 'Dirceu gordo'
	WHERE Id = 2

	UPDATE TESTE_SLEEPING
	SET Ds_Descricao = 'Dirceu gordo'
	WHERE Id = 2

	--	SELECT 4
-- ROLLBACK
GO


--	2) EXECUTAR O CODIGO ABAIXO EM OUTRA QUERY (QUERY 2)
USE Traces

SELECT * FROM TESTE_SLEEPING
GO

--	3) EXECUTAR A PROCEDURE "sp_whoisactive" PARA VERIFICAR O LOCK
EXEC sp_whoisactive

--	4) EXECUTAR O SELECT ABAIXO COM O "NOLOCK"
USE Traces

SELECT * FROM TESTE_SLEEPING WITH(NOLOCK)
GO

--	5) FAZER O ROLLBACK NA OUTRA QUERY

--	6) EXECUTAR NOVAMENTE O SELECT (COMENTAR SOBRE A LEITURA SUJA DO "NOLOCK")
USE Traces

SELECT * FROM TESTE_SLEEPING
GO